### PR TITLE
Ci/ubuntu 18

### PR DESCRIPTION
**Pull request by ixzzd**
I faced the GLIBC mismatch issue on Debian stable

> /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./rescript-react-intl-extractor)

Here is exactly the same issue that I had with rescript-vscode plugin:
https://github.com/rescript-lang/rescript-vscode/issues/216

GH actions `linux-latest` version was updated recently, Let's lock it on ubuntu 18.04 for now?

### CODE REVIEW

**Comment by cknitt** [comment]
Github is showing me again the changes that I merged already, strange.

What is the reason for ubuntu-18.04?

Also, because of the problems I had with esy on Windows, I am currently revamping build/CI/test to migrate away from esy and use opam directly, see #78.

**Comment by ixzzd** [comment]
> Github is showing me again the changes that I merged already, strange.

For me as well :grimacing: Not sure what's wrong, but I will try to fix it.

> What is the reason for ubuntu-18.04?

I propose to use `ubuntu-18.04` to get rid of Glibc mismatch issue (Debian 10, current stable, has Glibc 2.28)

**Comment by cknitt** [comment]
Ah, ok, I'll include the ubuntu-18.04 in my PR then.
I am planning to publish a release over the weekend BTW.

**Comment by cknitt** [comment]
ubuntu-18.04 is merged #78 already.

**Pull request closed without merging**
